---
title: "Last day before fall break/midterm"
author: "Becky Tang"
date: "Oct. 12, 2022"
output:
  xaringan::moon_reader:
    css: "math218-slides.css"
    logo: img/math218-sticker-icon.png
    lib_dir: libs/font-awesome
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
# R options
options(
  htmltools.dir.version = FALSE, # for blogdown
  show.signif.stars = FALSE,     # for regression output
  warm = 1
  )
# Set dpi and height for images
library(knitr)
opts_chunk$set(fig.height = 2.65, dpi = 300) 
# ggplot2 color palette with gray
color_palette <- list(gray = "#999999", 
                      salmon = "#E69F00", 
                      lightblue = "#56B4E9", 
                      green = "#009E73", 
                      yellow = "#F0E442", 
                      darkblue = "#0072B2", 
                      red = "#D55E00", 
                      purple = "#CC79A7")

options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(
	fig.align = "center",
	fig.height = 3.75,
	fig.width = 6.25,
	message = FALSE,
	warning = FALSE
)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(rvest)
```

## Outline for today

- Project description

- KNN implementation! 

--

## Housekeeping

- After class, please fill out this brief and anonymous survey: https://forms.gle/y5bw9xi5WiFpsAQY7

- No office hours next Tuesday (e-mail me for questions on the midterm)

- I am willing to hold extra hours tomorrow morning if critical mass will actually appear!