---
title: "Ultimate Candy Rankings - Model Selection"
date: "`r Sys.Date()`"
output: html_document
---

- In your R Markdown file, load the fivethirtyeight package along with other packages required for analysis. 

- We will use the `candy_rankings` dataset for this analysis. Type `??candy_rankings` to see the variable names and definitions. 

### Planning

Decide on a subset of 7 - 10 variables to consider for your analysis. 

- This list should include at least two interaction terms. Remember, 
we consider interactions when variables might behave differently for various 
levels of another variable. Ideally, you would get expert guidance for
choosing interactions.

- The more variables you consider the longer model selection will take so keep that in mind.


### Model fitting, selection, and interpretation

- Use backwards elimination to do model selection. Make sure to show 
each step of decision (though you don't have to interpret the models at 
each stage).
- Yes, this is tedious. And yes, there are ways of automating it. But for now, 
  go through the process "manually", to get a good sense of how the model 
  selection algorithm works.
- Provide interpretations for the slopes for the final model you arrive at 
and create at least one visualization that supports your narrative.