---
title: "Writing better code: Solutions"
date: "`r Sys.Date()`"
output: html_document
---


```{r load-packages, warning = FALSE, message = FALSE}
library(tidyverse)
```

Each exercise uses the `diamonds` data set in the ggplot2 package. 

### Exercise 1

*Task: Calculate the relative frequency of `cut` for each level of `color`*

#### Original Code

```{r ex1-orig-code}
diamonds %>%
 select(color) %>%
 unique()

# create separate DFs for each color
colorD <- diamonds %>%
 filter(color == "D")
colorE <- diamonds %>%
 filter(color == "E")
colorF <- diamonds %>%
 filter(color == "F")
colorG <- diamonds %>%
 filter(color == "G")
colorH <- diamonds %>%
 filter(color == "H")
colorI <- diamonds %>%
 filter(color == "I")
colorJ <- diamonds %>%
 filter(color == "J")

# calculate relative freq within each color df
relfreqD <- colorD %>%
 count(cut) %>%
 mutate(color = "D", rel_freq = n / sum(n))
relfreqE <- colorE %>%
 count(cut) %>%
 mutate(color = "E", rel_freq = n / sum(n))
relfreqF <- colorF %>%
 count(cut) %>%
 mutate(color = "F", rel_freq = n / sum(n))
relfreqG <- colorG %>%
 count(cut) %>%
 mutate(color = "G", rel_freq = n / sum(n))
relfreqH <- colorH %>%
 count(cut) %>%
 mutate(color = "H", rel_freq = n / sum(n))
relfreqI <- colorI %>%
 count(cut) %>%
 mutate(color = "I", rel_freq = n / sum(n))
relfreqJ <- colorJ %>%
 count(cut) %>%
 mutate(color = "J", rel_freq = n / sum(n))

# put it all together
bind_rows(relfreqD, relfreqE, relfreqF, relfreqG, relfreqH, relfreqI, relfreqJ) %>%
 select(-n)
```

#### Revised Code

```{r}
## Better way to do it ##
diamonds %>%
 count(color, cut) %>%
 group_by(color) %>%
 mutate(rel_freq = n/sum(n)) %>% 
  print(n = nrow(.)) #to show the whole tibble (only if necessary!)
```

### Exercise 2

*Task: Find the `color` with the highest median price.*

#### Original Code

```{r ex2-orig-code}

#function to calculate median price
calculate_median_price <- function(color_type) {
  diamonds %>%
    filter(color == color_type) %>%
    summarise(median(price)) %>%
    pull()
}

#get list of colors
unique_colors <- diamonds %>%
  select(color) %>%
  unique() %>%
  pull()

median_price_colors <- tibble(color = unique_colors, 
                              median = numeric(length(unique_colors)))

#calculate median price for each color
for (i in 1:length(unique_colors)) {
  median_price_colors[i, 2] <- calculate_median_price(unique_colors[i])
}

#find max
median_price_colors %>%
  filter(median == max(median)) %>%
  select(color, median)
```

#### Revised Code

```{r}
## One approach
 
diamonds %>%
  group_by(color) %>%
  summarise(median_price = median(price)) %>%
  filter(median_price == max(median_price)) %>%
  select(color, median_price)
```

```{r}
## Another approach
 
diamonds %>%
  group_by(color) %>%
  summarise(median_price = median(price)) %>%
  arrange(desc(median_price)) %>%
  slice(1)
```
